import {useCallback,useEffect,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,Alert,KeyboardAvoidingView,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {addProduct,listProducts,sellOne,purchaseStock,Product,addTask,listTasks,toggleTask,Task,addAsset,listAssets,Asset,addDraft,listDrafts,addCheck,listChecks,exportData,restoreData,addTransaction,listTransactions,Transaction,deleteTransaction,addBudget,listBudgets,Budget,addWallet,listWallets,Wallet,addDebt,listDebts,settleDebt,Debt,addContact,listContacts,Contact,addReminder,listReminders,Reminder,addNote,listNotes,Note,wealthSummary,businessSummary,exportCsvTransactions} from '../lib/database';
import {platforms,openPlatform,shareText} from '../lib/platforms';
import {rupiah,nominal} from '../lib/format';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Notifications from 'expo-notifications';
import * as DocumentPicker from 'expo-document-picker';

export default function ModulePage(){
 const router=useRouter();const params=useLocalSearchParams<{module:string}>();const id=String(params.module||'');
 const titles:Record<string,string>={money:'SATU Money',business:'SATU Business',social:'SATU Social',trust:'SATU Trust',assistant:'SATU AI',tasks:'Family & Team',wealth:'SATU Wealth',settings:'Pengaturan',automation:'SATU Automation',family:'Family & Team',reports:'Laporan SATUOS'};
 const title=titles[id]||'SATUOS';
 const [name,setName]=useState(''),[a,setA]=useState(''),[b,setB]=useState(''),[c,setC]=useState(''),[d,setD]=useState(''),[items,setItems]=useState<any[]>([]),[platform,setPlatform]=useState('WhatsApp'),[kind,setKind]=useState('pengeluaran'),[category,setCategory]=useState('Umum'),[answer,setAnswer]=useState('Asisten lokal berbasis aturan. Coba kata kunci saldo, stok, tugas, atau promosi.'),[backupText,setBackupText]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[subtab,setSubtab]=useState('transaksi'),[wallets,setWallets]=useState<Wallet[]>([]),[selectedWallet,setSelectedWallet]=useState<number|null>(null);
 const load=useCallback(async()=>{try{
  if(id==='money'){setWallets(await listWallets());if(subtab==='transaksi')setItems(await listTransactions());else if(subtab==='dompet')setItems(await listWallets());else if(subtab==='anggaran')setItems(await listBudgets(month));else if(subtab==='utang')setItems(await listDebts())}
  else if(id==='business'){if(subtab==='kontak')setItems(await listContacts(kind==='pemasukan'?'pelanggan':'pemasok'));else setItems(await listProducts())}
  else if(id==='tasks')setItems(await listTasks());else if(id==='wealth')setItems(await listAssets());else if(id==='social')setItems(await listDrafts());else if(id==='trust')setItems(await listChecks());else if(id==='automation')setItems(await listReminders());else if(id==='family')setItems(await listNotes())
 }catch(e){Alert.alert('Gagal memuat data',e instanceof Error?e.message:'Kesalahan')}} ,[id,subtab,month,kind]);
 useEffect(()=>{load()},[load]);
 const action=async()=>{try{
  if(id==='money'){
   if(subtab==='transaksi'){await addTransaction(kind==='pemasukan'?'pemasukan':'pengeluaran',name,nominal(a),category,selectedWallet);setName('');setA('')}
   else if(subtab==='dompet'){await addWallet(name,nominal(a));setName('');setA('')}
   else if(subtab==='anggaran'){await addBudget(name,nominal(a),month);setName('');setA('')}
   else if(subtab==='utang'){await addDebt(name,nominal(a),kind==='pemasukan'?'piutang':'utang',b);setName('');setA('');setB('')}
  }else if(id==='business'){
   if(subtab==='kontak'){await addContact(name,kind==='pemasukan'?'pelanggan':'pemasok',a,b);setName('');setA('');setB('')}
   else {await addProduct(name,nominal(a),nominal(b),Math.max(0,Math.floor(Number(c))));setName('');setA('');setB('');setC('')}
  }else if(id==='tasks'){await addTask(name);setName('')}
  else if(id==='wealth'){await addAsset(name,nominal(a));setName('');setA('')}
  else if(id==='social'){await addDraft(platform,a);setA('');Alert.alert('Draf tersimpan','Konten belum dipublikasikan.')}
  else if(id==='trust'){if(!name.trim())throw Error('Tempel URL atau pesan terlebih dahulu.');const reasons:string[]=[];if(/(otp|pin|kata sandi|password|kode verifikasi)/i.test(name))reasons.push('Meminta kode rahasia atau kredensial.');if(/(hadiah|menang|gratis).{0,50}(transfer|biaya admin)/i.test(name))reasons.push('Janji hadiah disertai permintaan pembayaran.');if(/bit\.ly|tinyurl\.com|t\.co/i.test(name))reasons.push('Tautan pemendek; periksa tujuan akhir.');if(/^http:\/\//i.test(name))reasons.push('Alamat menggunakan HTTP tanpa enkripsi TLS.');const verdict=reasons.length?'Perlu diwaspadai':'Tidak ditemukan pola umum';await addCheck(name,verdict,reasons.join('\n')||'Aturan lokal tidak menemukan pola umum; bukan jaminan aman.');setAnswer(verdict+'\n'+(reasons.join('\n')||'Tetap verifikasi pengirim dan domain.'));setName('')}
  else if(id==='assistant'){const q=name.toLowerCase();if(q.includes('stok')){const p=await listProducts();setAnswer(p.map(x=>x.name+': '+x.stock+' unit').join('\n')||'Belum ada produk.')}else if(q.includes('tugas')){const t=await listTasks();setAnswer(t.filter(x=>!x.done).map(x=>x.title).join('\n')||'Tidak ada tugas tertunda.')}else if(q.includes('saldo')||q.includes('keuangan')){const t=await listTransactions();const inc=t.filter(x=>x.kind==='pemasukan').reduce((n,x)=>n+x.amount,0),exp=t.filter(x=>x.kind==='pengeluaran').reduce((n,x)=>n+x.amount,0);setAnswer('Pemasukan tercatat: '+rupiah(inc)+'\nPengeluaran tercatat: '+rupiah(exp)+'\nSaldo bersih: '+rupiah(inc-exp))}else setAnswer('Saya asisten lokal berbasis aturan. Coba tanyakan saldo, stok, atau tugas.')}
  else if(id==='automation'){const when=new Date(b.trim().replace(' ','T'));if(!Number.isFinite(when.getTime())||when.getTime()<=Date.now())throw Error('Waktu harus valid dan berada di masa depan. Gunakan YYYY-MM-DD HH:mm.');await addReminder(name,when.toISOString());try{const permission=await Notifications.requestPermissionsAsync();if(permission.granted){await Notifications.setNotificationChannelAsync('satuos-pengingat',{name:'Pengingat SATUOS',importance:Notifications.AndroidImportance.DEFAULT});await Notifications.scheduleNotificationAsync({content:{title:'Pengingat SATUOS',body:name,sound:true},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:when,channelId:'satuos-pengingat'}});Alert.alert('Pengingat disimpan','Pengingat lokal dijadwalkan pada '+when.toLocaleString('id-ID'))}else Alert.alert('Pengingat disimpan','Izin notifikasi ditolak. Pengingat tersimpan, tetapi pemberitahuan tidak dijadwalkan.')}catch(e){Alert.alert('Pengingat disimpan','Data tersimpan, tetapi notifikasi tidak berhasil dijadwalkan. Periksa izin notifikasi perangkat.')}setName('');setB('')}
  else if(id==='family'){await addNote(name,a,'keluarga');setName('');setA('')}
  await load()
 }catch(e){Alert.alert('Tidak dapat menyimpan',e instanceof Error?e.message:'Kesalahan')}};
 const writeShare=async(filename:string,data:string,mimeType:string)=>{const uri=FileSystem.documentDirectory+filename;await FileSystem.writeAsStringAsync(uri,data,{encoding:FileSystem.EncodingType.UTF8});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType});else Alert.alert('Berkas dibuat',uri)};
 const backup=async()=>{try{await writeShare('satuos-cadangan.json',await exportData(),'application/json')}catch(e){Alert.alert('Ekspor gagal',e instanceof Error?e.message:'Kesalahan')}};
 const restore=async()=>{try{if(!backupText.trim())throw Error('Tempel isi berkas cadangan JSON terlebih dahulu.');Alert.alert('Konfirmasi pemulihan','Pemulihan akan mengganti data lokal pada tabel yang terdapat di cadangan. Ekspor cadangan saat ini terlebih dahulu.',[{text:'Batal',style:'cancel'},{text:'Pulihkan data',style:'destructive',onPress:async()=>{try{await restoreData(backupText);setBackupText('');Alert.alert('Pemulihan selesai','Data cadangan sudah dimasukkan.');await load()}catch(e){Alert.alert('Pemulihan gagal',e instanceof Error?e.message:'Kesalahan')}}}])}catch(e){Alert.alert('Tidak dapat memulihkan',e instanceof Error?e.message:'Kesalahan')}};
 const pickRestore=async()=>{try{const picked=await DocumentPicker.getDocumentAsync({type:['application/json','text/json','text/plain'],copyToCacheDirectory:true,multiple:false});if(picked.canceled)return;const file=picked.assets[0];const data=await FileSystem.readAsStringAsync(file.uri,{encoding:FileSystem.EncodingType.UTF8});setBackupText(data);Alert.alert('Cadangan dibuka','Berkas dimuat. Tekan Pulihkan data dari JSON untuk memeriksa dan mengimpor cadangan.')}catch(e){Alert.alert('Gagal membuka cadangan',e instanceof Error?e.message:'Kesalahan')}};
 const sell=async(p:Product)=>{try{await sellOne(p.id);await load();Alert.alert('Penjualan tercatat','Stok berkurang satu dan pemasukan dicatat.')}catch(e){Alert.alert('Gagal',e instanceof Error?e.message:'Kesalahan')}};
 const buy=async(p:Product)=>{try{await purchaseStock(p.id,1,p.cost);await load();Alert.alert('Pembelian dicatat','Stok bertambah satu dan biaya pembelian dicatat.')}catch(e){Alert.alert('Gagal',e instanceof Error?e.message:'Kesalahan')}};
 const tabs=(values:string[])=> <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginTop:16,marginBottom:8}}>{values.map(v=><Pressable key={v} onPress={()=>setSubtab(v)} style={[s.chip,subtab===v&&s.selected]}><Text style={s.buttonText}>{({transaksi:'Transaksi',dompet:'Dompet',anggaran:'Anggaran',utang:'Utang/piutang',kontak:'Kontak'})[v]||v}</Text></Pressable>)}</ScrollView>;
 const field=(value:string,set:(v:string)=>void,placeholder:string,keyboardType:any='default',multiline=false)=><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#718096" keyboardType={keyboardType} multiline={multiline} style={[s.input,multiline&&{minHeight:90}]}/>;
 const btn=(label:string,onPress:()=>void)=><Pressable style={s.button} onPress={onPress}><Text style={s.buttonText}>{label}</Text></Pressable>;
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={s.back}>← Kembali</Text></Pressable><Text style={s.title}>{title}</Text><Text style={s.sub}>Data lokal perangkat · status integrasi ditampilkan secara jujur.</Text>
 {id==='money'&&<>{tabs(['transaksi','dompet','anggaran','utang'])}
 {subtab==='transaksi'&&<><Text style={s.heading}>Catat transaksi</Text><View style={s.row}>{btn(kind==='pemasukan'?'✓ Pemasukan':'Pilih pemasukan',()=>setKind('pemasukan'))}{btn(kind==='pengeluaran'?'✓ Pengeluaran':'Pilih pengeluaran',()=>setKind('pengeluaran'))}</View>{field(name,setName,'Keterangan transaksi')}{field(a,setA,'Nominal Rupiah','decimal-pad')}{field(category,setCategory,'Kategori, mis. Makan atau Gaji')}<Text style={s.sub}>Pilih dompet (opsional)</Text><View style={s.row}>{btn(selectedWallet===null?'✓ Tanpa dompet':'Tanpa dompet',()=>setSelectedWallet(null))}{wallets.map(w=><Pressable key={w.id} style={[s.chip,selectedWallet===w.id&&s.selected]} onPress={()=>setSelectedWallet(w.id)}><Text style={s.buttonText}>{w.name}</Text></Pressable>)}</View>{btn('Simpan transaksi',action)}<Text style={s.heading}>Riwayat transaksi</Text>{items.map((t:Transaction)=><View key={t.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{t.title}</Text><Text style={s.sub}>{t.kind} · {t.category} · {t.created_at}</Text><Text style={[s.amount,{color:t.kind==='pemasukan'?'#6EE7B7':'#FDA4AF'}]}>{t.kind==='pemasukan'?'+':'−'}{rupiah(t.amount)}</Text></View><Pressable style={s.small} onPress={()=>Alert.alert('Hapus transaksi?','Tindakan ini tidak dapat dibatalkan.',[{text:'Batal',style:'cancel'},{text:'Hapus',style:'destructive',onPress:async()=>{await deleteTransaction(t.id);await load()}}])}><Text style={s.buttonText}>Hapus</Text></Pressable></View>)}{btn('Ekspor transaksi CSV',async()=>{try{await writeShare('satuos-transaksi.csv',await exportCsvTransactions(),'text/csv')}catch(e){Alert.alert('Ekspor gagal',String(e))}})}</>}
 {subtab==='dompet'&&<>{field(name,setName,'Nama dompet')}{field(a,setA,'Saldo awal Rupiah','decimal-pad')}{btn('Tambah dompet',action)}{items.map((w:Wallet)=><View key={w.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{w.name}</Text><Text style={s.sub}>Saldo awal {rupiah(w.opening_balance)}</Text></View><Text style={s.amount}>{rupiah(w.balance)}</Text></View>)}<Text style={s.sub}>Transaksi umum belum dialokasikan ke dompet. Saldo dompet hanya menghitung transaksi yang terhubung ke dompet.</Text></>}
 {subtab==='anggaran'&&<>{field(month,setMonth,'Bulan YYYY-MM')}{field(name,setName,'Kategori anggaran')}{field(a,setA,'Batas anggaran Rupiah','decimal-pad')}{btn('Simpan anggaran',action)}{items.map((v:Budget)=><View key={v.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{v.category} · {v.month}</Text><Text style={s.sub}>Terpakai {rupiah(v.spent)} dari {rupiah(v.amount)}</Text></View><Text style={[s.amount,{color:v.spent>v.amount?'#FDA4AF':'#6EE7B7'}]}>{v.amount?Math.round(v.spent/v.amount*100):0}%</Text></View>)}</>}
 {subtab==='utang'&&<>{btn(kind==='pemasukan'?'Mode piutang':'Mode utang',()=>setKind(kind==='pemasukan'?'pengeluaran':'pemasukan'))}{field(name,setName,'Keterangan utang/piutang')}{field(a,setA,'Nominal Rupiah','decimal-pad')}{field(b,setB,'Jatuh tempo (YYYY-MM-DD)')}{btn('Simpan catatan',action)}{items.map((v:Debt)=><View key={v.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{v.kind==='utang'?'Utang':'Piutang'} · {v.title}</Text><Text style={s.sub}>{v.due_date||'Tanpa jatuh tempo'} · {v.paid?'Lunas':'Belum lunas'}</Text><Text style={s.amount}>{rupiah(v.amount)}</Text></View>{!v.paid&&<Pressable style={s.small} onPress={async()=>{await settleDebt(v.id);await load()}}><Text style={s.buttonText}>Lunasi</Text></Pressable>}</View>)}</>}
 </>}
 {id==='business'&&<>{tabs(['produk','kontak'])}{subtab==='kontak'?<><View style={s.row}>{btn(kind==='pemasukan'?'✓ Pelanggan':'Pelanggan',()=>setKind('pemasukan'))}{btn(kind==='pengeluaran'?'✓ Pemasok':'Pemasok',()=>setKind('pengeluaran'))}</View>{field(name,setName,'Nama pelanggan/pemasok')}{field(a,setA,'Nomor telepon (opsional)')}{field(b,setB,'Catatan (opsional)')}{btn('Simpan kontak',action)}{items.map((x:Contact)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{x.name}</Text><Text style={s.sub}>{x.kind} · {x.phone} · {x.notes}</Text></View></View>)}</>:<><Text style={s.heading}>Tambah produk</Text>{field(name,setName,'Nama produk')}{field(a,setA,'Harga jual','decimal-pad')}{field(b,setB,'Harga modal','decimal-pad')}{field(c,setC,'Stok awal','number-pad')}{btn('Simpan produk',action)}<Text style={s.heading}>Katalog dan stok</Text>{items.map((p:Product)=><View key={p.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{p.name}</Text><Text style={s.sub}>{rupiah(p.price)} · Stok {p.stock} · Modal {rupiah(p.cost)}</Text><Text style={s.sub}>Margin/unit {rupiah(p.price-p.cost)} · Total stok modal {rupiah(p.cost*p.stock)}</Text></View><View>{<Pressable style={s.small} onPress={()=>sell(p)} disabled={p.stock<1}><Text style={s.buttonText}>Jual 1</Text></Pressable>}<Pressable style={s.small} onPress={()=>buy(p)}><Text style={s.buttonText}>Beli +1</Text></Pressable></View></View>)}</>}</>}
 {id==='tasks'&&<>{field(name,setName,'Nama tugas')}{btn('Tambah tugas',action)}<Text style={s.heading}>Daftar tugas</Text>{items.map((t:Task)=><Pressable key={t.id} style={s.item} onPress={async()=>{await toggleTask(t.id,!t.done);await load()}}><Text style={s.itemTitle}>{t.done?'✓ ':'○ '}{t.title}</Text></Pressable>)}</>}
 {id==='wealth'&&<>{field(name,setName,'Nama aset')}{field(a,setA,'Nilai rupiah','decimal-pad')}{btn('Simpan aset',action)}{items.map((x:Asset)=><View key={x.id} style={s.item}><Text style={s.itemTitle}>{x.title}</Text><Text style={s.amount}>{rupiah(x.value)}</Text></View>)}<View style={s.card}><Text style={s.heading}>Kekayaan bersih</Text><Text style={s.sub}>Ringkasan dihitung dari aset dan catatan utang/piutang aktif.</Text>{btn('Hitung ringkasan',async()=>{const v=await wealthSummary();setAnswer('Total aset: '+rupiah(v.assets)+'\nUtang: '+rupiah(v.liabilities)+'\nPiutang: '+rupiah(v.receivables)+'\nKekayaan bersih: '+rupiah(v.net))})}<Text style={s.answer}>{answer}</Text></View></>}
 {id==='social'&&<><Text style={s.heading}>Koneksi Platform</Text>{platforms.map(p=><View key={p.name} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{p.name}</Text><Text style={s.sub}>{p.features} · Belum terhubung</Text></View><Pressable style={s.small} onPress={()=>openPlatform(p.url).catch(e=>Alert.alert('Gagal membuka',String(e)))}><Text style={s.buttonText}>Buka</Text></Pressable></View>)}<Text style={s.heading}>Draf promosi</Text><ScrollView horizontal>{platforms.slice(0,5).map(p=><Pressable key={p.name} onPress={()=>setPlatform(p.name)} style={[s.chip,platform===p.name&&s.selected]}><Text style={s.buttonText}>{p.name}</Text></Pressable>)}</ScrollView>{field(a,setA,'Tulis caption','default',true)}<View style={s.row}>{btn('Simpan draf',action)}{btn('Bagikan',()=>shareText(a).catch(e=>Alert.alert('Berbagi gagal',String(e))))}</View>{items.map((v:any)=><View key={v.id} style={s.item}><Text style={s.itemTitle}>{v.platform} · {v.status}</Text><Text style={s.sub}>{v.caption}</Text></View>)}</>}
 {id==='trust'&&<><Text style={s.sub}>Pemeriksaan aturan lokal, bukan reputasi real-time dan bukan jaminan suatu tautan aman.</Text>{field(name,setName,'Tempel URL atau pesan','default',true)}{btn('Periksa',action)}<Text style={s.answer}>{answer}</Text>{items.map((x:any)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{x.verdict}</Text><Text style={s.sub}>{x.target}</Text><Text style={s.sub}>{x.reasons}</Text></View></View>)}</>}
 {id==='assistant'&&<><Text style={s.answer}>{answer}</Text>{field(name,setName,'Tanya saldo, stok, atau tugas')}{btn('Tanya asisten',action)}</>}
 {id==='automation'&&<><Text style={s.sub}>Pengingat disimpan lokal. Notifikasi terjadwal belum diaktifkan di versi ini.</Text>{field(name,setName,'Judul pengingat')}{field(b,setB,'Waktu (contoh 2026-10-10 18:00)')}{btn('Simpan pengingat',action)}{items.map((v:Reminder)=><View key={v.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{v.title}</Text><Text style={s.sub}>{v.due_at}</Text></View></View>)}</>}
 {id==='family'&&<>{field(name,setName,'Judul catatan keluarga')}{field(a,setA,'Isi catatan','default',true)}{btn('Simpan catatan',action)}{items.map((v:Note)=><View key={v.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{v.title}</Text><Text style={s.sub}>{v.body}</Text></View></View>)}</>}
 {id==='reports'&&<><View style={s.card}><Text style={s.heading}>Laporan usaha</Text><Text style={s.sub}>Ringkasan dihitung dari catatan penjualan, harga modal produk saat transaksi, pembelian stok, dan stok saat ini.</Text>{btn('Perbarui laporan',async()=>{const v=await businessSummary();const t=await listTransactions();const inc=t.filter(x=>x.kind==='pemasukan').reduce((n,x)=>n+x.amount,0);const exp=t.filter(x=>x.kind==='pengeluaran').reduce((n,x)=>n+x.amount,0);setAnswer('Omzet penjualan: '+rupiah(v.revenue)+'\\nPerkiraan harga pokok barang terjual: '+rupiah(v.soldCost)+'\\nLaba kotor perkiraan: '+rupiah(v.grossProfit)+'\\nPembelian stok tercatat: '+rupiah(v.purchases)+'\\nUnit terjual: '+v.units+'\\nProduk dengan stok 3 atau kurang: '+v.lowStock+'\\n\\nSemua pemasukan: '+rupiah(inc)+'\\nSemua pengeluaran tercatat: '+rupiah(exp)+'\\nArus bersih dari transaksi: '+rupiah(inc-exp))})}<Text style={s.answer}>{answer}</Text>{btn('Ekspor transaksi CSV',async()=>{try{await writeShare('satuos-transaksi.csv',await exportCsvTransactions(),'text/csv')}catch(e){Alert.alert('Ekspor gagal',String(e))}})}</View><View style={s.card}><Text style={s.heading}>Catatan akurasi</Text><Text style={s.sub}>Laba kotor dihitung dari harga modal produk yang tersimpan ketika penjualan dicatat. Perubahan harga modal di masa depan tidak mengubah catatan penjualan lama. Laporan pajak dan akuntansi resmi belum disediakan.</Text></View></>}
 {id==='settings'&&<><View style={s.card}><Text style={s.heading}>Cadangan data</Text><Text style={s.sub}>Ekspor seluruh tabel lokal ke JSON. Simpan berkas dengan aman.</Text>{btn('Ekspor cadangan JSON',backup)}<Text style={s.heading}>Pulihkan cadangan</Text><Text style={s.sub}>Buka berkas JSON cadangan dengan aplikasi teks, salin isinya, lalu tempel di bawah. Pemulihan mengganti data lokal pada tabel yang ada di cadangan.</Text>{field(backupText,setBackupText,'Tempel isi JSON cadangan','default',true)}{btn('Pilih berkas cadangan JSON',pickRestore)}{btn('Pulihkan data dari JSON',restore)}{btn('Ekspor transaksi CSV',async()=>{try{await writeShare('satuos-transaksi.csv',await exportCsvTransactions(),'text/csv')}catch(e){Alert.alert('Ekspor gagal',String(e))})}</View><View style={s.card}><Text style={s.heading}>Privasi dan koneksi</Text><Text style={s.sub}>Database inti lokal. Sinkronisasi cloud, login sosial, notifikasi terjadwal, dan penerbitan otomatis belum aktif. Jangan masukkan PIN bank atau kata sandi sosial.</Text></View></>}
 </ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B1220'},page:{padding:20,maxWidth:760,width:'100%',alignSelf:'center',paddingBottom:45},back:{color:'#93C5FD',fontWeight:'700',marginBottom:18},title:{fontSize:27,fontWeight:'900',color:'#F8FAFC'},sub:{color:'#94A3B8',fontSize:12,marginTop:5,lineHeight:18},heading:{fontSize:18,fontWeight:'800',color:'#F1F5F9',marginTop:22,marginBottom:12},input:{backgroundColor:'#111C2E',borderColor:'#26364D',borderWidth:1,borderRadius:12,padding:14,color:'#F8FAFC',marginBottom:10},button:{backgroundColor:'#2563EB',padding:13,borderRadius:12,alignItems:'center',marginTop:4,marginRight:7,marginBottom:8},buttonText:{color:'#F8FAFC',fontWeight:'800'},item:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:13,borderBottomColor:'#24334A',borderBottomWidth:1},itemTitle:{color:'#F1F5F9',fontWeight:'800',flex:1},amount:{color:'#F1F5F9',fontWeight:'900',marginTop:4},small:{backgroundColor:'#1D3556',padding:10,borderRadius:10,marginBottom:5},row:{flexDirection:'row',flexWrap:'wrap',gap:5},chip:{backgroundColor:'#172337',padding:10,borderRadius:10,marginRight:8,marginTop:10},selected:{backgroundColor:'#1D4ED8'},answer:{backgroundColor:'#13233B',borderRadius:14,padding:16,color:'#F1F5F9',lineHeight:22,marginVertical:14},card:{backgroundColor:'#111C2E',borderColor:'#26364A',borderWidth:1,borderRadius:16,padding:16,marginTop:16}});
