import {useCallback,useEffect,useState} from 'react';
import {ScrollView,View,Text,Pressable,StyleSheet,useWindowDimensions,RefreshControl} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useRouter,Href} from 'expo-router';
import NetInfo from '@react-native-community/netinfo';
import {summary} from '../lib/database';
import {rupiah} from '../lib/format';
import BottomNav from '../components/BottomNav';
const modules:{title:string;desc:string;route:Href;icon:string}[]=[{title:'SATU Money',desc:'Keuangan pribadi',route:'/money',icon:'Rp'},{title:'SATU Business',desc:'Produk dan penjualan',route:'/business',icon:'UM'},{title:'SATU Social',desc:'Draf dan koneksi platform',route:'/social',icon:'↗'},{title:'SATU Trust',desc:'Pemeriksaan pola mencurigakan',route:'/trust',icon:'✓'},{title:'SATU AI',desc:'Asisten lokal berbasis aturan',route:'/assistant',icon:'AI'},{title:'Family & Team',desc:'Tugas dan catatan keluarga',route:'/family',icon:'☷'},{title:'SATU Wealth',desc:'Aset dan kewajiban',route:'/wealth',icon:'◆'},{title:'SATU Automation',desc:'Pengingat dan jadwal lokal',route:'/automation',icon:'⏰'},{title:'Laporan SATUOS',desc:'Laporan usaha dan arus kas',route:'/reports',icon:'▤'},{title:'Pengaturan',desc:'Privasi dan cadangan',route:'/settings',icon:'⚙'}];
export default function Home(){const router=useRouter();const {width}=useWindowDimensions();const [totals,setTotals]=useState({income:0,expense:0,balance:0});const [dbError,setDbError]=useState<string|null>(null);const [online,setOnline]=useState<boolean|null>(null);const [refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{setTotals(await summary());setDbError(null)}catch(e){setDbError(e instanceof Error?e.message:'Database lokal belum dapat dibuka')}} ,[]);useEffect(()=>{load();const sub=NetInfo.addEventListener(s=>setOnline(!!s.isConnected));return sub},[load]);const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor="#FF9F0A"/>}><View style={s.top}><View><Text style={s.brand}>SATUOS</Text><Text style={s.sub}>Satu Aplikasi, Banyak Solusi.</Text></View><Text style={s.online}>{online===null?'Memeriksa…':online?'● Online':'● Offline'}</Text></View>{dbError&&<View style={s.errorCard}><Text style={s.errorTitle}>Data belum bisa dimuat</Text><Text style={s.errorText}>{dbError}</Text><Pressable onPress={load}><Text style={s.link}>Coba lagi</Text></Pressable></View>}<View style={s.hero}><Text style={s.eyebrow}>RINGKASAN KEUANGAN</Text><Text style={s.balance}>{rupiah(totals.balance)}</Text><Text style={s.sub}>Saldo bersih dari transaksi yang dicatat</Text><View style={s.row}><View style={{flex:1}}><Text style={s.sub}>Pemasukan</Text><Text style={s.green}>{rupiah(totals.income)}</Text></View><View style={{flex:1}}><Text style={s.sub}>Pengeluaran</Text><Text style={s.red}>{rupiah(totals.expense)}</Text></View></View></View><Text style={s.heading}>Ruang kerja</Text><View style={s.grid}>{modules.map(m=><Pressable key={m.title} onPress={()=>router.push(m.route)} style={[s.module,{width:width<380?'100%':(width-52)/2}]}><View style={s.icon}><Text style={s.iconText}>{m.icon}</Text></View><Text style={s.moduleTitle}>{m.title}</Text><Text style={s.sub}>{m.desc}</Text><Text style={s.link}>Buka modul →</Text></Pressable>)}</View><Text style={s.footer}>Data inti tersimpan lokal · Tidak perlu akun cloud</Text></ScrollView><BottomNav/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0B1220'},page:{padding:20,paddingBottom:35,maxWidth:900,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},brand:{fontSize:28,fontWeight:'900',letterSpacing:3,color:'#F8FAFC'},sub:{color:'#94A3B8',fontSize:12,marginTop:4},online:{color:'#6EE7B7',fontSize:12,fontWeight:'800'},hero:{backgroundColor:'#17191F',borderColor:'#2D2D35',borderWidth:1,borderRadius:22,padding:20,marginBottom:25},eyebrow:{color:'#FFB020',fontWeight:'800',fontSize:11,letterSpacing:1.5},balance:{color:'#F8FAFC',fontSize:29,fontWeight:'900',marginTop:10},row:{flexDirection:'row',gap:20,marginTop:18},green:{color:'#6EE7B7',fontWeight:'800',marginTop:5},red:{color:'#FDA4AF',fontWeight:'800',marginTop:5},heading:{color:'#F8FAFC',fontSize:19,fontWeight:'800',marginBottom:13},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},module:{backgroundColor:'#17191F',borderColor:'#2B2D34',borderWidth:1,borderRadius:17,padding:15,minHeight:145},icon:{width:36,height:36,borderRadius:11,backgroundColor:'#342515',alignItems:'center',justifyContent:'center',marginBottom:11},iconText:{color:'#FFB020',fontWeight:'900'},moduleTitle:{color:'#F1F5F9',fontSize:15,fontWeight:'800'},link:{color:'#FF9F0A',fontWeight:'800',fontSize:12,marginTop:12},errorCard:{backgroundColor:'#351A1A',borderColor:'#7F1D1D',borderWidth:1,borderRadius:14,padding:14,marginBottom:16},errorTitle:{color:'#FCA5A5',fontWeight:'900',fontSize:14},errorText:{color:'#FECACA',fontSize:12,marginTop:5},footer:{color:'#64748B',fontSize:11,textAlign:'center',marginTop:24}});
