import * as SQLite from 'expo-sqlite';
let promise: Promise<SQLite.SQLiteDatabase> | undefined;
export async function db(){ if(!promise) promise=SQLite.openDatabaseAsync('satuos.db'); const d=await promise; await d.execAsync(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL CHECK(kind IN ('pemasukan','pengeluaran')), title TEXT NOT NULL, amount REAL NOT NULL CHECK(amount>=0), category TEXT NOT NULL DEFAULT 'Umum', created_at TEXT NOT NULL DEFAULT (datetime('now'))); CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,cost REAL NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT (datetime('now'))); CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,done INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (datetime('now'))); CREATE TABLE IF NOT EXISTS assets(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,value REAL NOT NULL DEFAULT 0,kind TEXT NOT NULL DEFAULT 'aset'); CREATE TABLE IF NOT EXISTS drafts(id INTEGER PRIMARY KEY AUTOINCREMENT,platform TEXT NOT NULL,caption TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Draf',created_at TEXT NOT NULL DEFAULT (datetime('now'))); CREATE TABLE IF NOT EXISTS trust_checks(id INTEGER PRIMARY KEY AUTOINCREMENT,target TEXT NOT NULL,verdict TEXT NOT NULL,reasons TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now'))); INSERT OR IGNORE INTO migrations(version,applied_at) VALUES(1,datetime('now'));`); return d; }
export type Transaction={id:number;kind:string;title:string;amount:number;category:string;created_at:string};
export type Product={id:number;name:string;price:number;cost:number;stock:number;updated_at:string};
export type Task={id:number;title:string;done:number};
export type Asset={id:number;title:string;value:number;kind:string};
export async function addTransaction(kind:'pemasukan'|'pengeluaran',title:string,amount:number,category='Umum'){await(await db()).runAsync('INSERT INTO transactions(kind,title,amount,category) VALUES(?,?,?,?)',kind,title.trim(),amount,category)}
export async function listTransactions():Promise<Transaction[]>{return(await db()).getAllAsync<Transaction>('SELECT * FROM transactions ORDER BY id DESC LIMIT 100')}
export async function summary(){const r=await(await db()).getFirstAsync<{income:number;expense:number}>("SELECT COALESCE(SUM(CASE WHEN kind='pemasukan' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN kind='pengeluaran' THEN amount ELSE 0 END),0) expense FROM transactions");return{income:r?.income??0,expense:r?.expense??0,balance:(r?.income??0)-(r?.expense??0)}}
export async function addProduct(name:string,price:number,cost:number,stock:number){await(await db()).runAsync('INSERT INTO products(name,price,cost,stock) VALUES(?,?,?,?)',name.trim(),price,cost,stock)}
export async function listProducts():Promise<Product[]>{return(await db()).getAllAsync<Product>('SELECT * FROM products ORDER BY name COLLATE NOCASE')}
export async function sellOne(id:number){const d=await db();await d.withTransactionAsync(async()=>{const p=await d.getFirstAsync<Product>('SELECT * FROM products WHERE id=?',id);if(!p)throw Error('Produk tidak ditemukan.');if(p.stock<1)throw Error('Stok tidak mencukupi.');await d.runAsync('UPDATE products SET stock=stock-1 WHERE id=?',id);await d.runAsync("INSERT INTO transactions(kind,title,amount,category) VALUES('pemasukan',?,?,?)",'Penjualan: '+p.name,p.price,'Penjualan')})}
export async function addTask(title:string){await(await db()).runAsync('INSERT INTO tasks(title) VALUES(?)',title.trim())}
export async function listTasks():Promise<Task[]>{return(await db()).getAllAsync<Task>('SELECT * FROM tasks ORDER BY done,id DESC')}
export async function toggleTask(id:number,done:boolean){await(await db()).runAsync('UPDATE tasks SET done=? WHERE id=?',done?1:0,id)}
export async function addAsset(title:string,value:number,kind:string){await(await db()).runAsync('INSERT INTO assets(title,value,kind) VALUES(?,?,?)',title.trim(),value,kind)}
export async function listAssets():Promise<Asset[]>{return(await db()).getAllAsync<Asset>('SELECT * FROM assets ORDER BY rowid DESC')}
export async function addDraft(platform:string,caption:string){await(await db()).runAsync('INSERT INTO drafts(platform,caption) VALUES(?,?)',platform,caption.trim())}
export async function listDrafts(){return(await db()).getAllAsync<{id:number;platform:string;caption:string;status:string}>('SELECT * FROM drafts ORDER BY id DESC')}
export async function addCheck(target:string,verdict:string,reasons:string){await(await db()).runAsync('INSERT INTO trust_checks(target,verdict,reasons) VALUES(?,?,?)',target,verdict,reasons)}
export async function listChecks(){return(await db()).getAllAsync<{id:number;target:string;verdict:string;reasons:string}>('SELECT * FROM trust_checks ORDER BY id DESC LIMIT 50')}
export async function exportData(){const d=await db();const [transactions,products,tasks,assets,drafts,checks]=await Promise.all([d.getAllAsync('SELECT * FROM transactions'),d.getAllAsync('SELECT * FROM products'),d.getAllAsync('SELECT * FROM tasks'),d.getAllAsync('SELECT * FROM assets'),d.getAllAsync('SELECT * FROM drafts'),d.getAllAsync('SELECT * FROM trust_checks')]);return JSON.stringify({format:'SATUOS-CADANGAN',version:1,exportedAt:new Date().toISOString(),transactions,products,tasks,assets,drafts,checks},null,2)}
